EvaluatingWebsitePerformance/Controllers/ArchiveController.cs
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AutoMapper;
using EvaluatingWebsitePerformance.Common.DTO;
using EvaluatingWebsitePerformance.ViewModel;

namespace EvaluatingWebsitePerformance.Controllers
{
    public class ArchiveController : BaseController<WebsiteDto>
    {
        public ActionResult Index()
        {
            var mainPages = Mapper.Map<IEnumerable<WebsiteDto>, IEnumerable<WebsiteViewModel>>(handler.GetAll().Where(i => i.ParentId == 0));

            return View(mainPages);
        }

        public JsonResult GetArchive(int id)
        {
            var newList = new List<WebsiteDto>();
            var allWebsites = handler.GetAll().ToList();
            var list = allWebsites.Where(i => i.ParentId == id).ToList();
            for (int i = 0; i < list.Count; i++)
            {
                for (int j = 0; j < allWebsites.Count; j++)
                {
                    if (list[i].Id == allWebsites[j].ParentId)
                    {
                        newList.Add(allWebsites[j]);
                    }

                }
            }
            newList.AddRange(list);
            newList.Add(allWebsites.FirstOrDefault(i => i.Id == id));

            return Json(newList, JsonRequestBehavior.AllowGet);
        }
    }
}

EvaluatingWebsitePerformance/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")

    <script src="~/wwwroot/lib/jquery-1.11.1/dist/jquery.min.js"></script>
    <script src="~/wwwroot/lib/Chart-js/dist/Chart.js"></script>
    <script src="~/Scripts/perfomance.js"></script>
    <script src="~/Scripts/graph.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Evaluating Website Performance", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Get archive data", "Index", "Archive")</li>
                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    
    @RenderSection("scripts", required: false)
</body>
</html>